on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: averissimo/cuddly-octo-system@main
        with:
          path-to-shiny-app: 
            - 'inst/examples/app/test1'
      
